version: "3.3"
services:
  # postgres:
  #   image: postgres:12.2
  #   container_name: postgres
  #   restart: unless-stopped
  #   platform: linux/amd64
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   ports:
  #     - 5434:5432
  #   environment:
  #     - POSTGRES_PASSWORD=password321
  #     - POSTGRES_USER=user-node
  #     - POSTGRES_DB=db-postgre
  api:
    # depends_on:
    #   - postgres
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - .:/app/node_app
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - notused:/app/node_modules
    env_file:
      - .env
volumes:
  pgdata: {}
  notused: {}
